### ISSUE TITLE
Column visibility

### ISSUE THREAD

**Issue by jt196** [vincjo/datatables#35]
Is there any way to change the visibility of a column? I'm working with about 5 columns, and would like to hide 2 of them when the screen with is reduced to mobile/tablet size. 

I seem to be able to pass class into the Th components, but CSS `display: none` doesn't apply for some reason.

**Comment by vincjo** [comment]
It seems to work with media queries
I made an example:
https://vincjo.fr/datatables/test/media-query
(you must downsize the viewport to see the change)

".maskbable" class is added in `Th`, `ThFilters` and `td`
````css
    @media (max-width: 1200px) {
        .resizable {
            width: 280px;
        }
        .resizable :global(.maskable) {
            display: none;
        }
    }
````
